# Generated by Django 4.1.5 on 2023-01-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='user',
        ),
        migrations.AddField(
            model_name='exchange',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
