# Generated by Django 4.1.5 on 2023-01-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt', '0004_remove_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
